#!/usr/local/bin/perl
# -------------------------------------------------------------
# utiliza a tabela users para sugerir nomes de especialistas
# -------------------------------------------------------------
$|=1;
use strict;
use JSON;
use lib "../../lib";
use GUARDIOES;
my $cfg = new GUARDIOES();

my $par = $cfg->param();

my $search_string = lc $par->data('name');
   $search_string =~ s/^\s+|\s+$//g; $search_string =~ s/\s+/ /g;

if ($search_string)
{ my $sql = $cfg->connect();
  my $limit = 35;

  my $where = '';
  foreach (split(' ',$search_string)) { $where .= "unaccent(name) ~* unaccent('^$_| $_') and " }
  $where =~ s/ and $//;
  

  my $cmd = <<EOM;
select	distinct name, email
from	users
where	
	$where
	and status != 'inativo'
	and (category = 'especialista' or category = 'admin' or category = 'super')
order by 1
limit $limit
EOM

  my %p = $sql->query($cmd);

  my $hash = { results => [] };

  foreach my $i (0..$sql->nRecords-1)
  { $p{$i}{'name'} =~ s/\s+/ /g; $p{$i}{'name'} =~ s/^\s+|\s+$//g;

    push @{$hash->{'results'}}, { id => $i, info => "$p{$i}{'email'}", value => $p{$i}{'name'} };
  }

  my $json = new JSON();
  print "Content-Type: application/json\n\n".$json->encode( $hash );
}
