#!/usr/local/bin/perl
# -----------------------------------------------------
# cria a página /indicators (indicadores)
# -----------------------------------------------------
$|=1;
use strict;
use lib "../lib";
use GUARDIOES;

my $cfg = new GUARDIOES();

my $par = $cfg->parameters();

my $user = $cfg->get_user_info();

my $script = <<EOM;
<script src="/js/Chartjs/Chart.bundle.min.js"></script>
<script src="/js/indicators_v1.js"></script>
<style>
canvas { -moz-user-select: none;
         -webkit-user-select: none;
         -ms-user-select: none;
       }
</style>
<link rel="stylesheet" href="/css/dhtmlx.css" type="text/css"> 
<script src="/js/dhtmlx.js" type="text/javascript"></script>
EOM
print $cfg->html_head({ script => $script });
my $dic = $cfg->dic();

print $cfg->div_top_banner({ page => 'about', sub_page => 'indicators' });

my $sql = $cfg->connect();

# getting min & max dates from db

my $date_ini = ''; my $date_fim = '';
my $cmd = <<EOM;
select min(min_date),max(max_date) from
(	select min(since)		as min_date,max(since) as max_date from users
	union
	select min(record_date)		as min_date,max(record_date) as max_date from record
	union
	select min(dateidentified)	as min_date,max(dateidentified) as max_date from ident
) foo
EOM
my %p = $sql->query($cmd);
if ($p{0}{'min'} =~ /(\d{4}\-\d{2}\-\d{2})/) { $date_ini = $1 }
if ($p{0}{'max'} =~ /(\d{4}\-\d{2}\-\d{2})/) { $date_fim = $1 }

# analysing parameters

$date_ini = sprintf("%04d-%02d-%02d", $par->{'year_ini'}, ($par->{'month_ini'} ||  1), ($par->{'day_ini'} ||  1)) if $par->{'year_ini'};
$date_fim = sprintf("%04d-%02d-%02d", $par->{'year_fim'}, ($par->{'month_fim'} || 12), ($par->{'day_fim'} || $cfg->maxDayOf(($par->{'month_fim'} || 12),$par->{'year_fim'}))) if $par->{'year_fim'};

my $mask = 'month';
   $mask = 'day' if $par->{'month_ini'} || $par->{'month_fim'};
#   $mask = 'day'   if $par->{'day_ini'}   || $par->{'day_fim'};

my %color = ();
foreach ('A','B','C','D')
{ $color{$_}{'border'}     = $cfg->rgba($cfg->{'palette_color'}{"--svg-".$_});
  $color{$_}{'background'} = $cfg->rgba($cfg->{'palette_color'}{"--svg-".$_},0.5);
}

#------------------------------------------------------------  users by period

my $cmd = <<EOM;
select date_trunc('$mask',since) as date,count(1) from users where since between '$date_ini' and '$date_fim' group by 1 order by 1;
EOM

my %p = $sql->query($cmd);
print STDERR $sql->message if $sql->error;

my $labels = ''; my $values = ''; my $total = 0;
foreach (0..$sql->nRecords-1)
{ if ($p{$_}{'date'} =~ /^(\d+)\-(\d+)\-(\d+)/)
  { 
    $labels .= "'".($mask eq 'month' ? "$2/$1" : "$3/$2/$1")."',";

    $total += $p{$_}{'count'};
    $values .= "'$total',";
  }
}
$labels =~ s/,$//; $values =~ s/,$//;

my $users_graph = <<EOM;
<canvas id="usersDiv" style='width: 450px; height: 350px'></canvas>
<script type="text/javascript">
	var usersDiv_ctx = document.getElementById('usersDiv').getContext('2d');

	var usersDiv_data =
			{ labels: [$labels],
                          datasets: [
				{ label: '$dic->{'usersInTime'}',
				  backgroundColor: '$color{'A'}{'background'}',
				  borderColor:     '$color{'A'}{'border'}',
				  borderWidth: 1,
				  data: [$values],
				  labels: [$labels],
				} ]

                	};
	var usersDiv_options = {
				responsive: true,
				legend: { display: false, position: 'bottom' },
				title: { display: true, text: '$dic->{'usersInTime'}', padding: 30, fontFamily: 'Helvetica', fontStyle: 'bold', fontSize: 16, fontColor: '$cfg->{'palette_color'}{'--title-h2'}' },
				scales: { xAxes: [{ ticks: { min: 0 }, gridLines: { display: false } }], yAxes: [{ ticks: { min: 0 }, gridLines: { display: false } }] }
                           };
</script>
EOM

# ------------------------------------------------------------ records by period

my $cmd = <<EOM;
select date_trunc('$mask',record_date) as date,count(1) from record where record_date between '$date_ini' and '$date_fim' group by 1 order by 1;
EOM

my %p = $sql->query($cmd);
print STDERR $sql->message if $sql->error;

my $labels = ''; my $values = ''; my $total = 0;
foreach (0..$sql->nRecords-1)
{ if ($p{$_}{'date'} =~ /^(\d+)\-(\d+)\-(\d+)/)
  { my $label = "$1/$2";
    $labels .= "'$label',";

    $total += $p{$_}{'count'};
    $values .= "'$total',";
  }
}
$labels =~ s/,$//; $values =~ s/,$//;

my $recs_graph = <<EOM;
<canvas id="recsDiv" style='width: 450px; height: 350px'></canvas>
<script type="text/javascript">
	var recsDiv_ctx = document.getElementById('recsDiv').getContext('2d');

	var recsDiv_data =
			{ labels: [$labels],
                          datasets: [
				{ label: '$dic->{'recordsInTime'}',
				  backgroundColor: '$color{'B'}{'background'}',
				  borderColor:     '$color{'B'}{'border'}',
				  borderWidth: 1,
				  data: [$values],
				  labels: [$labels],
				} ]

                	};
	var recsDiv_options = {	responsive: true,
				legend: { display: false, position: 'bottom' },
				title: { display: true, text: '$dic->{'recordsInTime'}', padding: 30, fontFamily: 'Helvetica', fontStyle: 'bold', fontSize: 16, fontColor: '$cfg->{'palette_color'}{'--title-h2'}' },
				scales: { xAxes: [{ ticks: { min: 0 }, gridLines: { display: false } }], yAxes: [{ ticks: { min: 0 }, gridLines: { display: false } }] }
                           };

</script>
EOM

my $xml;
#------------------------------------------------------------  identifications of animals by period

my $cmd = <<EOM;
select date_trunc('$mask',dateidentified) as date,count(1) from ident where dateidentified between '$date_ini' and '$date_fim' and kingdom = 'animalia' group by 1 order by 1;
EOM

my %p = $sql->query($cmd);
print STDERR $sql->message if $sql->error;

my $labels = ''; my $values = ''; my $total = 0;
foreach (0..$sql->nRecords-1)
{ if ($p{$_}{'date'} =~ /^(\d+)\-(\d+)\-(\d+)/)
  { my $label = "$1/$2";
    $labels .= "'$label',";

    $total += $p{$_}{'count'};
    $values .= "'$total',";
  }
}
$labels =~ s/,$//; $values =~ s/,$//;

my $ids_animalia_graph = <<EOM;
<canvas id="idsAnimaliaDiv" style='width: 450px; height: 350px'></canvas>
<script type="text/javascript">
	var idsAnimaliaDiv_ctx = document.getElementById('idsAnimaliaDiv').getContext('2d');

	var idsAnimaliaDiv_data =
			{ labels: [$labels],
                          datasets: [
				{ label: '$dic->{'recordsInTime'}',
				  backgroundColor: '$color{'C'}{'background'}',
				  borderColor:     '$color{'C'}{'border'}',
				  borderWidth: 1,
				  data: [$values],
				  labels: [$labels],
				} ]

                	};
	var idsAnimaliaDiv_options = {	responsive: true,
				legend: { display: false, position: 'bottom' },
				title: { display: true, text: '$dic->{'idsAnimaliaInTime'}', padding: 30, fontFamily: 'Helvetica', fontStyle: 'bold', fontSize: 16, fontColor: '$cfg->{'palette_color'}{'--title-h2'}' },
				scales: { xAxes: [{ ticks: { min: 0 }, gridLines: { display: false } }], yAxes: [{ ticks: { min: 0 }, gridLines: { display: false } }] }
                           };

</script>
EOM
#--------------------------------------------------------  identifications of plants by period

my $cmd = <<EOM;
select date_trunc('$mask',dateidentified) as date,count(1) from ident where dateidentified between '$date_ini' and '$date_fim' and kingdom = 'plantae' group by 1 order by 1;
EOM

my %p = $sql->query($cmd);
print STDERR $sql->message if $sql->error;

my $labels = ''; my $values = ''; my $total = 0;
foreach (0..$sql->nRecords-1)
{ if ($p{$_}{'date'} =~ /^(\d+)\-(\d+)\-(\d+)/)
  { my $label = "$1/$2";
    $labels .= "'$label',";

    $total += $p{$_}{'count'};
    $values .= "'$total',";
  }
}
$labels =~ s/,$//; $values =~ s/,$//;

my $ids_plantae_graph = <<EOM;
<canvas id="idsPlantaeDiv" style='width: 450px; height: 350px'></canvas>
<script type="text/javascript">
	var idsPlantaeDiv_ctx = document.getElementById('idsPlantaeDiv').getContext('2d');

	var idsPlantaeDiv_data =
			{ labels: [$labels],
                          datasets: [
				{ label: '$dic->{'recordsInTime'}',
				  backgroundColor: '$color{'D'}{'background'}',
				  borderColor:     '$color{'D'}{'border'}',
				  borderWidth: 1,
				  data: [$values],
				  labels: [$labels],
				} ]

                	};
	var idsPlantaeDiv_options = {	responsive: true,
				legend: { display: false, position: 'bottom' },
				title: { display: true, text: '$dic->{'idsPlantaeInTime'}', padding: 30, fontFamily: 'Helvetica', fontStyle: 'bold', fontSize: 16, fontColor: '$cfg->{'palette_color'}{'--title-h2'}' },
				scales: { xAxes: [{ ticks: { min: 0 }, gridLines: { display: false } }], yAxes: [{ ticks: { min: 0 }, gridLines: { display: false } }] }
                           };

</script>
EOM
#------------------------------------------------------------ 

# ini
my $day_ini_opts = "<option value=''>$dic->{'day'}</option>";
   foreach (1..31) { my $sel = " selected='true'" if $par->{'day_ini'} == $_; $day_ini_opts .= "<option value='$_'$sel>$_</option>" }

my $month_ini_opts = "<option value=''>$dic->{'month'}</option>";
   foreach (1..12)
   { my $sel = " selected='true'" if $par->{'month_ini'} == $_;
     $month_ini_opts .= "<option value='$_'$sel>".
		($cfg->{'user_lang'} eq 'en' ?
                        ('','Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec')[$_] :
                        ('','Jan','Fev','Mar','Abr','Mai','Jun','Jul','Ago','Set','Out','Nov','Dez')[$_])."</option>";
   }

my $year_ini_opts = "<option value=''>$dic->{'year'}</option>";
foreach (2017..2018) { my $sel = " selected='true'" if $par->{'year_ini'} == $_; $year_ini_opts .= "<option value='$_'$sel>$_</option>" }

# fim
my $day_fim_opts = "<option value=''>$dic->{'day'}</option>";
   foreach (1..31) { my $sel = " selected='true'" if $par->{'day_fim'} == $_; $day_fim_opts .= "<option value='$_'$sel>$_</option>" }

my $month_fim_opts = "<option value=''>$dic->{'month'}</option>";
   foreach (1..12)
   { my $sel = " selected='true'" if $par->{'month_fim'} == $_;
     $month_fim_opts .= "<option value='$_'$sel>".
		($cfg->{'user_lang'} eq 'en' ?
                        ('','Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec')[$_] :
                        ('','Jan','Fev','Mar','Abr','Mai','Jun','Jul','Ago','Set','Out','Nov','Dez')[$_])."</option>";
   }

my $year_fim_opts = "<option value=''>$dic->{'year'}</option>";
foreach (2017..2018) { my $sel = " selected='true'" if $par->{'year_fim'} == $_; $year_fim_opts .= "<option value='$_'$sel>$_</option>" }

if ($date_ini =~ /(\d+)\-(\d+)\-(\d+)/) { $date_ini = "$3-$2-$1" }
if ($date_fim =~ /(\d+)\-(\d+)\-(\d+)/) { $date_fim = "$3-$2-$1" }

print <<EOM;
<div id='divMain'>
<form name='indicatorsForm' id='indicatorsForm' method='post' enctype='multipart/form-data'>
<center>
<table>
<tr>
    <td class='pad15'>$users_graph</td>
    <td class='pad15'>$recs_graph</td>
</tr>
<tr>
    <td class='pad15'>$ids_plantae_graph</td>
    <td class='pad15'>$ids_animalia_graph</td>
</tr>

<tr><td class='small embaixo'>$date_ini $dic->{'to'} $date_fim</td>
<td>
<table>
<tr>
    <td align='right'>
	<table>	<tr class='acima'>	<td>$dic->{'from'}</td>
			<td><select id='day_ini' name='day_ini'>$day_ini_opts</select></td>
    			<td><select id='month_ini' name='month_ini'>$month_ini_opts</select></td>
    			<td><select id='year_ini' name='year_ini'>$year_ini_opts</select><span> <img id="ini_icon" src="/imgs/calendar.png" border="0"></span></td>
		</tr>
	</table>
    </td>
    <td align='left'>
	<table>	<tr class='acima'>	<td>$dic->{'to'}</td>
			<td><select id='day_fim' name='day_fim'>$day_fim_opts</select></td>
    			<td><select id='month_fim' name='month_fim'>$month_fim_opts</select></td>
    			<td><select id='year_fim' name='year_fim'>$year_fim_opts</select><span> <img id="fim_icon" src="/imgs/calendar.png" border="0"></span></td>
    <td class='no_meio'><input type='button' value='$dic->{'send'}' onclick="submitIndicatorsForm('$dic->{'indicatorsFormError'}')" class='send'/></td>
		</tr>
	</table>
    </td>
</tr>
</table></td>
</tr>
</table>
</center>
</form>
<script>
	window.onload = function() {
		window.recsDiv_graph = new Chart(recsDiv_ctx,	{ type: 'line', data: recsDiv_data, options: recsDiv_options });
		window.usersDiv_graph = new Chart(usersDiv_ctx, { type: 'line', data: usersDiv_data, options: usersDiv_options });
		window.idsAnimaliaDiv_graph = new Chart(idsAnimaliaDiv_ctx, { type: 'line', data: idsAnimaliaDiv_data, options: idsAnimaliaDiv_options });
		window.idsPlantaeDiv_graph = new Chart(idsPlantaeDiv_ctx, { type: 'line', data: idsPlantaeDiv_data, options: idsPlantaeDiv_options });

          // Calendarios
          dhtmlXCalendarObject.prototype.langData["pt"] = {
            // date format for inputs
            dateformat: "%d/%m/%Y",
            // header format
            hdrformat: "%F %Y",
            // full names of months
            monthesFNames: ["Janeiro","Fevereiro","Março","Abril","Maio","Junho",
                            "Julho","Agosto","Setembro","Outubro","Novembro","Dezembro"],
            // short names of months
            monthesSNames: ["Jan","Fev","Mar","Abr","Mai","Jun",
                            "Jul","Ago","Set","Out","Nov","Dez"],
            // full names of days
            daysFNames: ["Segunda","Terça","Quarta","Quinta",
                         "Sexta","Sábado","Domingo"],
            // short names of days
            daysSNames: ["Dom", "Seg","Ter","Qua","Qui","Sex","Sab"],
            // starting day of a week. Number from 1(Monday) to 7(Sunday)
            weekstart: 1,
            // the title of the week number column
            weekname: "S",
            // name of the "Today" button
            today: "Hoje",
            // name of the "Clear" button
            clear: "Limpar"
          };
          var myCalendar1 = new dhtmlXCalendarObject({button:"ini_icon"});
          myCalendar1.loadUserLanguage("pt");
          myCalendar1.hideTime();
          var myEvent = myCalendar1.attachEvent("onClick", function(){
            var d1 = myCalendar1.getDate();
            document.getElementById('year_ini').value = d1.getFullYear().toString();
            document.getElementById('month_ini').value = (d1.getMonth()+1).toString();
            document.getElementById('day_ini').value = d1.getDate().toString();
          });
          var myCalendar2 = new dhtmlXCalendarObject({button:"fim_icon"});
          myCalendar2.loadUserLanguage("pt");
          myCalendar2.hideTime();
          var myEvent = myCalendar2.attachEvent("onClick", function(){
            var d2 = myCalendar2.getDate();
            document.getElementById('year_fim').value = d2.getFullYear().toString();
            document.getElementById('month_fim').value = (d2.getMonth()+1).toString();
            document.getElementById('day_fim').value = d2.getDate().toString();
          });
	};
</script>
EOM

#if ($date_ini =~ /(\d+)\-(\d+)\-(\d+)/) { $date_ini = "$3-$2-$1" }
#if ($date_fim =~ /(\d+)\-(\d+)\-(\d+)/) { $date_fim = "$3-$2-$1" }
#
#print "<br/><span class='small'>$dic->{'from'} $date_ini $dic->{'to'} $date_fim</span><br/>\n";
print $cfg->html_foot();
