#!/usr/local/bin/perl
$|=1;
use strict;
use lib "../lib";
use GUARDIOES;

my $cfg = new GUARDIOES();
my $dic = $cfg->dic();
my $par = $cfg->param();


my ($status,$pass) = $cfg->reset_password($ENV{'PATH_INFO'});

if ($status)
{ my $msg = $status == 1 ? "Senha alterada para <h2>$pass</h2>" :
	  $status == 2 ? "Link fora da validade / Link no longer valid" : 'Error';
  print $cfg->html_head();
  print $cfg->div_top_banner();
	

  print <<EOM;
<center>
<div id='divLogin'>
$msg
</div>
</center>
</body>
</html>
EOM
}
else
{ print <<EOM;
Location: $cfg->{'home_url'}

EOM
}
