#!/usr/local/bin/perl
$|=1;
use strict;
use lib "../lib";
use GUARDIOES;

my $page = $ARGV[0] || 'terms_especialista';

my $cfg = new GUARDIOES({ loginRequired => 0 });

print $cfg->html_head();

print $cfg->get_page({ page => $page });
